services:
  redis:
    image: redis:7
    container_name: feedback-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - feedback-network

  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=feedback.settings
      - DEBUG=True
      - PYTHONPATH=/app
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - feedback-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  static_volume:
  media_volume:

networks:
  feedback-network:
    driver: bridge
