# Generated by Django 5.2.4 on 2025-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedbackstatus_status_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstatus',
            name='name',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
