# Generated by Django 5.2.4 on 2025-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_feedbackstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstatus',
            name='status_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='type_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='priority',
            name='priority_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
