# Generated by Django 5.2.4 on 2025-08-12 09:17


from django.db import migrations


def create_initial_choices(apps, schema_editor):
    FeedbackType = apps.get_model("feedbacks", "FeedbackType")
    Priority = apps.get_model("feedbacks", "Priority")
    FeedbackStatus = apps.get_model("feedbacks", "FeedbackStatus")

    # Tạo các loại feedback
    FeedbackType.objects.create(name="suggestion", description="Góp ý")
    FeedbackType.objects.create(name="bug", description="Báo lỗi")
    FeedbackType.objects.create(name="other", description="Khác")

    # Tạo các mức độ ưu tiên
    Priority.objects.create(name="low")
    Priority.objects.create(name="medium")
    Priority.objects.create(name="high")

    # Tạo các trạng thái
    FeedbackStatus.objects.create(name="pending")
    FeedbackStatus.objects.create(name="processing")
    FeedbackStatus.objects.create(name="resolved")
    FeedbackStatus.objects.create(name="closed")


def delete_initial_choices(apps, schema_editor):
    FeedbackType = apps.get_model("feedbacks", "FeedbackType")
    Priority = apps.get_model("feedbacks", "Priority")
    FeedbackStatus = apps.get_model("feedbacks", "FeedbackStatus")

    FeedbackType.objects.all().delete()
    Priority.objects.all().delete()
    FeedbackStatus.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [("feedbacks", "0004_alter_feedbackstatus_status_id_and_more")]

    operations = [
        migrations.RunPython(create_initial_choices, delete_initial_choices),
    ]
