# Generated by Django 5.2.4 on 2025-08-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_auto_20250812_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
