# Generated by Django 5.2.4 on 2025-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_rename_sent_at_emaillog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktype',
            name='name',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('bug', 'Bug'), ('other', 'Other')], default='suggestion', max_length=50),
        ),
    ]
