# Generated by Django 5.2.4 on 2025-08-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_alter_feedbacktype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_url',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
